# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foobar/v1alpha1/foobar.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'foobar/v1alpha1/foobar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66oobar/v1alpha1/foobar.proto\x12\x0f\x66oobar.v1alpha1\"\x1d\n\x0b\x45\x63hoRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"8\n\x0c\x45\x63hoResponse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message2R\n\tFoobarAPI\x12\x45\n\x04\x45\x63ho\x12\x1c.foobar.v1alpha1.EchoRequest\x1a\x1d.foobar.v1alpha1.EchoResponse\"\x00\x42\x35P\x01Z1github.com/vinea-dev/gengo/foobar/v1alpha1;foobarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foobar.v1alpha1.foobar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z1github.com/vinea-dev/gengo/foobar/v1alpha1;foobar'
  _globals['_ECHOREQUEST']._serialized_start=49
  _globals['_ECHOREQUEST']._serialized_end=78
  _globals['_ECHORESPONSE']._serialized_start=80
  _globals['_ECHORESPONSE']._serialized_end=136
  _globals['_FOOBARAPI']._serialized_start=138
  _globals['_FOOBARAPI']._serialized_end=220
# @@protoc_insertion_point(module_scope)
