# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from foobar.v1alpha1 import foobar_pb2 as foobar_dot_v1alpha1_dot_foobar__pb2


class FoobarAPIStub(object):
    """FoobarAPI is a simple example service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
                '/foobar.v1alpha1.FoobarAPI/Echo',
                request_serializer=foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest.SerializeToString,
                response_deserializer=foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse.FromString,
                _registered_method=True)


class FoobarAPIServicer(object):
    """FoobarAPI is a simple example service.
    """

    def Echo(self, request, context):
        """Echo is a simple RPC that echoes the request ID in the response,
        along with a message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FoobarAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest.FromString,
                    response_serializer=foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foobar.v1alpha1.FoobarAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('foobar.v1alpha1.FoobarAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FoobarAPI(object):
    """FoobarAPI is a simple example service.
    """

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foobar.v1alpha1.FoobarAPI/Echo',
            foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest.SerializeToString,
            foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
