# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: foobar/v1alpha1/foobar.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import foobar.v1alpha1.foobar_pb2 as foobar_dot_v1alpha1_dot_foobar__pb2


class FoobarAPI(Protocol):
    async def echo(self, request: foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest, ctx: RequestContext) -> foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class FoobarAPIASGIApplication(ConnectASGIApplication):
    def __init__(self, service: FoobarAPI, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/foobar.v1alpha1.FoobarAPI/Echo": Endpoint.unary(
                    method=MethodInfo(
                        name="Echo",
                        service_name="foobar.v1alpha1.FoobarAPI",
                        input=foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest,
                        output=foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.echo,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/foobar.v1alpha1.FoobarAPI"


class FoobarAPIClient(ConnectClient):
    async def echo(
        self,
        request: foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Echo",
                service_name="foobar.v1alpha1.FoobarAPI",
                input=foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest,
                output=foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class FoobarAPISync(Protocol):
    def echo(self, request: foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest, ctx: RequestContext) -> foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class FoobarAPIWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: FoobarAPISync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/foobar.v1alpha1.FoobarAPI/Echo": EndpointSync.unary(
                    method=MethodInfo(
                        name="Echo",
                        service_name="foobar.v1alpha1.FoobarAPI",
                        input=foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest,
                        output=foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.echo,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/foobar.v1alpha1.FoobarAPI"


class FoobarAPIClientSync(ConnectClientSync):
    def echo(
        self,
        request: foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Echo",
                service_name="foobar.v1alpha1.FoobarAPI",
                input=foobar_dot_v1alpha1_dot_foobar__pb2.EchoRequest,
                output=foobar_dot_v1alpha1_dot_foobar__pb2.EchoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
