# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: edge/v1alpha1/edge_api.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import edge.v1alpha1.edge_api_pb2 as edge_dot_v1alpha1_dot_edge__api__pb2


class EdgeAPI(Protocol):
    def register(self, request: edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest, ctx: RequestContext) -> AsyncIterator[edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def subscribe(self, request: edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest, ctx: RequestContext) -> edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EdgeAPIASGIApplication(ConnectASGIApplication):
    def __init__(self, service: EdgeAPI, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/edge.v1alpha1.EdgeAPI/Register": Endpoint.server_stream(
                    method=MethodInfo(
                        name="Register",
                        service_name="edge.v1alpha1.EdgeAPI",
                        input=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest,
                        output=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.register,
                ),
                "/edge.v1alpha1.EdgeAPI/Subscribe": Endpoint.unary(
                    method=MethodInfo(
                        name="Subscribe",
                        service_name="edge.v1alpha1.EdgeAPI",
                        input=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest,
                        output=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.subscribe,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/edge.v1alpha1.EdgeAPI"


class EdgeAPIClient(ConnectClient):
    def register(
        self,
        request: edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Register",
                service_name="edge.v1alpha1.EdgeAPI",
                input=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest,
                output=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def subscribe(
        self,
        request: edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Subscribe",
                service_name="edge.v1alpha1.EdgeAPI",
                input=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest,
                output=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class EdgeAPISync(Protocol):
    def register(self, request: edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest, ctx: RequestContext) -> Iterator[edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def subscribe(self, request: edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest, ctx: RequestContext) -> edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EdgeAPIWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: EdgeAPISync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/edge.v1alpha1.EdgeAPI/Register": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="Register",
                        service_name="edge.v1alpha1.EdgeAPI",
                        input=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest,
                        output=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.register,
                ),
                "/edge.v1alpha1.EdgeAPI/Subscribe": EndpointSync.unary(
                    method=MethodInfo(
                        name="Subscribe",
                        service_name="edge.v1alpha1.EdgeAPI",
                        input=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest,
                        output=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.subscribe,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/edge.v1alpha1.EdgeAPI"


class EdgeAPIClientSync(ConnectClientSync):
    def register(
        self,
        request: edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Register",
                service_name="edge.v1alpha1.EdgeAPI",
                input=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest,
                output=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def subscribe(
        self,
        request: edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Subscribe",
                service_name="edge.v1alpha1.EdgeAPI",
                input=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest,
                output=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
