# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edge/v1alpha1/edge_api.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'edge/v1alpha1/edge_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65\x64ge/v1alpha1/edge_api.proto\x12\redge.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\"@\n\x0fRegisterRequest\x12-\n\x12\x64\x65vice_fingerprint\x18\x01 \x01(\tR\x11\x64\x65viceFingerprint\"\"\n\x10RegisterResponse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"b\n\x10SubscribeRequest\x12\x19\n\x08\x61gent_id\x18\x01 \x01(\tR\x07\x61gentId\x12\x33\n\x07timeout\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationR\x07timeout\"\x80\x01\n\x11SubscribeResponse\x12\x15\n\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n\x0cjob_describe\x18\x02 \x01(\tR\x0bjobDescribe\x12\x31\n\x08job_type\x18\x03 \x01(\x0e\x32\x16.edge.v1alpha1.JobTypeR\x07jobType*;\n\x07JobType\x12\x18\n\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12JOB_TYPE_SCHEDULED\x10\x01\x32\xac\x01\n\x07\x45\x64geAPI\x12O\n\x08Register\x12\x1e.edge.v1alpha1.RegisterRequest\x1a\x1f.edge.v1alpha1.RegisterResponse\"\x00\x30\x01\x12P\n\tSubscribe\x12\x1f.edge.v1alpha1.SubscribeRequest\x1a .edge.v1alpha1.SubscribeResponse\"\x00\x42\x31P\x01Z-github.com/vinea-dev/gengo/edge/v1alpha1;edgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge.v1alpha1.edge_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z-github.com/vinea-dev/gengo/edge/v1alpha1;edge'
  _globals['_JOBTYPE']._serialized_start=412
  _globals['_JOBTYPE']._serialized_end=471
  _globals['_REGISTERREQUEST']._serialized_start=79
  _globals['_REGISTERREQUEST']._serialized_end=143
  _globals['_REGISTERRESPONSE']._serialized_start=145
  _globals['_REGISTERRESPONSE']._serialized_end=179
  _globals['_SUBSCRIBEREQUEST']._serialized_start=181
  _globals['_SUBSCRIBEREQUEST']._serialized_end=279
  _globals['_SUBSCRIBERESPONSE']._serialized_start=282
  _globals['_SUBSCRIBERESPONSE']._serialized_end=410
  _globals['_EDGEAPI']._serialized_start=474
  _globals['_EDGEAPI']._serialized_end=646
# @@protoc_insertion_point(module_scope)
