# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from edge.v1alpha1 import edge_api_pb2 as edge_dot_v1alpha1_dot_edge__api__pb2


class EdgeAPIStub(object):
    """EdgeAPI is a service for edge devices to connect and receive jobs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_stream(
                '/edge.v1alpha1.EdgeAPI/Register',
                request_serializer=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest.SerializeToString,
                response_deserializer=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_unary(
                '/edge.v1alpha1.EdgeAPI/Subscribe',
                request_serializer=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse.FromString,
                _registered_method=True)


class EdgeAPIServicer(object):
    """EdgeAPI is a service for edge devices to connect and receive jobs.
    """

    def Register(self, request, context):
        """Register registers an agent with the server and returns a stream of
        responses, starting with the agent's ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe is a long-polling RPC for an agent to receive jobs from the
        server. It waits until a job is available or the timeout is reached.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_stream_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest.FromString,
                    response_serializer=edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest.FromString,
                    response_serializer=edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edge.v1alpha1.EdgeAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edge.v1alpha1.EdgeAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdgeAPI(object):
    """EdgeAPI is a service for edge devices to connect and receive jobs.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/edge.v1alpha1.EdgeAPI/Register',
            edge_dot_v1alpha1_dot_edge__api__pb2.RegisterRequest.SerializeToString,
            edge_dot_v1alpha1_dot_edge__api__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edge.v1alpha1.EdgeAPI/Subscribe',
            edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeRequest.SerializeToString,
            edge_dot_v1alpha1_dot_edge__api__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
